name: Code Review

on: [pull_request]

jobs:

  # -- ESLINT -----------------------------------------------------------------
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@5d5d34225d930d298d52ae60999ca9b617dd2e3a
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run ESLint
        uses: reviewdog/action-eslint@94d539484aab48e9b2ffff6466d8866ee4e4b217 # v1.18.2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -- DOCKER -----------------------------------------------------------------
  # hadolint:
  #   name: Hadolint
  #   runs-on: ubuntu-latest

  #   steps:
      # - name: Harden GitHub Actions Runner
      #   uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
      #   with:
      #     egress-policy: audit

  #     - name: Checkout
  #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

  #     - name: Run hadolint
  #       uses: reviewdog/action-hadolint@55be5d2c4b0b80d439247b128a9ded3747f92a29 # tag=v1.33.0
  #       env:
  #         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
