name: Code Review

on: [pull_request]

jobs:

  # -- ESLINT -----------------------------------------------------------------
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@1d9871f0c592ab955b91e5744892890950701a87
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Run ESLint
        uses: reviewdog/action-eslint@0d9c815b089d06d77f6a6aad28e9d3bcd83896e5 # v1.18.1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -- DOCKER -----------------------------------------------------------------
  # hadolint:
  #   name: Hadolint
  #   runs-on: ubuntu-latest

  #   steps:
      # - name: Harden GitHub Actions Runner
      #   uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
      #   with:
      #     egress-policy: audit

  #     - name: Checkout
  #       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

  #     - name: Run hadolint
  #       uses: reviewdog/action-hadolint@55be5d2c4b0b80d439247b128a9ded3747f92a29 # tag=v1.33.0
  #       env:
  #         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
